name: tmate Session

on:
  workflow_dispatch:

jobs:
  tmate:
    runs-on: ubuntu-latest
    steps:
      - name: Run tmate
        run: |
          curl -fsSL https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz | tar -xJ
          sudo mv tmate-2.4.0-static-linux-amd64/tmate /usr/local/bin/
          tmate new-session -d
          tmate wait tmate-ready
          echo "Connect to runner:"
          tmate display -p '#{tmate_ssh}'
          sleep 3600
