name: SSH Tunnel

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Create SSH Tunnel
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no -R 9090:localhost:9090 -N root@193.31.117.165 -p 9011 &
          echo "Tunnel is running"
          sleep 21600
