name: Direct Tunnel

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Direct SSH Tunnel
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no -R 9098:localhost:9098 -N root@193.31.117.165 -p 9011 &
          echo "Tunnel is running"
          sleep 21600
