name: SSH Tunnel

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Test SSH Connection
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 root@193.31.117.165 -p 9011 "echo 'SSH connection successful'"
